name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Fix git
      run: git config --global core.autocrlf input

    - uses: actions/checkout@v2
    
    - name: Install Cygwin Action
      # You may pin to the exact commit or the version.
      # uses: cygwin/cygwin-install-action@49f298a7ebb00d4b3ddf58000c3e78eff5fbd6b9
      uses: cygwin/cygwin-install-action@v2
      with:
          packages: >-
                make
                libtool
                gcc-core
                gcc-g++
                gcc-objc
                gcc-objc++
  
    - name: Bootstrap
      run: bash ./bootstrap.sh

    - name: Configure and build
      run: bash ./build.sh

    - name: Test executable
      run: C:\cygwin\usr\local\bin\iperf3.exe -v

    - name: Archive executable
      uses: actions/upload-artifact@v3
      with:
        name: executable
        path: |
          C:\cygwin\usr\local\bin\iperf3.exe
          C:\cygwin\bin\cygwin1.dll