name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Fix git
      run: git config --global core.autocrlf input

    - uses: actions/checkout@v2
    
    - name: Install Cygwin Action
      # You may pin to the exact commit or the version.
      # uses: cygwin/cygwin-install-action@49f298a7ebb00d4b3ddf58000c3e78eff5fbd6b9
      uses: cygwin/cygwin-install-action@v2
    
    - name: Print current dir
      run: pwd
  
    - name: Configure
      run: bash ./configure

    - name: Print current dir content
      run: ls

    - name: Build
      run: bash make
      